version: '2'
services:
  drupal-web:
    build: ./web/
    ports:
      - "8081:80"
      - "8021:22"
    links:
      - solr
    environment:
      MYSQL_DATABASE: dev1
      MYSQL_ROOT_PASSWORD: pasa
      MYSQL_USER: roots
      MYSQL_PASSWORD: pss
      MYSQL_HOST: 192.168.148.199
      GIT_USER: sde
      GIT_PASSWORD: gh
      FILENAME: dev1.sql.gz
      UPDATE_DB: 0
      GIT_BRANCH: stage
      FTP: 0
    volumes:
      - /drupal/web-dev/files/dev1/htmlroot:/var/www/html
  solr:
    build: ./solr/
    ports:
      - "8981:8983"
    volumes:
      - /drupal/web-dev/files/dev1/solr:/opt/solr-4.10.4/example/solr/collection1/data
